name: ls_gfn
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1v=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.16=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - viennarna=2.4.13=py37hdbcaa40_2
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==1.4.0
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - astunparse==1.6.3
      - attrdict==2.0.1
      - attrs==23.1.0
      - biopython==1.81
      - boto3==1.28.19
      - botocore==1.31.19
      - cachetools==5.3.1
      - charset-normalizer==3.2.0
      - click==8.1.6
      - cloudpickle==2.2.1
      - cma==3.3.0
      - decorator==5.1.1
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - editdistance==0.6.2
      - filelock==3.12.2
      - flatbuffers==23.5.26
      - flexs==0.2.8
      - frozenlist==1.3.3
      - gast==0.4.0
      - gin-config==0.5.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - google-auth==2.22.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.56.2
      - gym==0.23.0
      - gym-notices==0.0.8
      - h5py==3.8.0
      - idna==3.4
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.3.1
      - jsonschema==4.17.3
      - keras==2.11.0
      - libclang==16.0.6
      - lmdb==1.4.1
      - markdown==3.4.4
      - markupsafe==2.1.3
      - msgpack==1.0.5
      - networkx==2.6.3
      - numpy==1.21.6
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.1
      - pandas==1.3.5
      - pathtools==0.1.2
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - polyleven==0.8
      - protobuf==3.19.6
      - psutil==5.9.5
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      # - pyg-lib==0.2.0+pt113cu117
      - pygame==2.1.3
      - pyparsing==3.1.1
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0.1
      - ray==2.6.2
      - rdkit==2023.3.2
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - s3transfer==0.6.1
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - sentry-sdk==1.29.2
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - tape-proteins==0.5
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.33.0
      - tensorflow-probability==0.19.0
      - termcolor==2.3.0
      - tf-agents==0.16.0
      - threadpoolctl==3.1.0
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.65.0
      - typing-extensions==4.7.1
      - urllib3==1.26.16
      - wandb==0.15.8
      - werkzeug==2.2.3
      - wrapt==1.15.0
      - zipp==3.15.0
